output-format: grouped

strictness: veryhigh
test-warnings: false
doc-warnings: false
member-warnings: true
inherits:
  - default
ignore-paths:
  - fixers
  - Utils/combinatorics.py
autodetect: false
max-line-length: 120

pycodestyle:
  disable:
  - N801
  - N802
  - N803
  - N806
  - N816
  - E126

pylint:
  disable:
  - invalid-name
  - use-list-literal
  - use-dict-literal

vulture:
  run: true